name: Maven Build and Selenium Tests on Push

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        java-version: 19
        distribution: adopt

    - name: Install ChromeDriver
      run: |
        #VERSION=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE`
        VERSION=`curl -s https://chromedriver.storage.googleapis.com/112.0.5615.49`
        wget https://chromedriver.storage.googleapis.com/$VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        chmod +x chromedriver
        sudo mv chromedriver /usr/local/bin
    - name: Build and Test with Maven
      run: mvn -B clean verify -DskipTests=false -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: target/surefire-reports/
